version: "3.8"
services:
  calculator-api:
    build:
      context: .
      dockerfile: backend_rpi4/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
  # volumes:
  #   - ./backend_rpi4:/app/backend_rpi4

  # caddy:
  #   image: caddy:2
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config

#volumes:
#  caddy_data:
#  caddy_config:
